modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"

[[mods]]
modId = "visor_susbrush"
version = "${version}"
displayName = "VisorSuspiciousBrush"
authors = "Weever"
displayTest = "NONE"
description = '''
An immersive Visor addon that lets you physically interact with sus blocks using brush in VR
'''

[[dependencies.visor_susbrush]]
modId = "visor"
mandatory = true
versionRange = "[0.3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.visor_susbrush]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.visor_susbrush]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "AFTER"
side = "BOTH"